edition = "2024"
style_edition = "2024"
tab_spaces = 4
trailing_semicolon = true
trailing_comma = "Vertical"
brace_style = "PreferSameLine"
max_width = 150
array_width = 100
attr_fn_like_width = 100
binop_separator = "Front"
chain_width = 100
comment_width = 100
enum_discrim_align_threshold = 20
fn_call_width = 100
fn_params_layout = "Tall"
fn_single_line = true
format_code_in_doc_comments = true
imports_layout = "Mixed"
indent_style = "Block"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
single_line_if_else_max_width = 70
single_line_let_else_max_width = 70
struct_field_align_threshold = 30
type_punctuation_density = "Wide"
unstable_features = true
where_single_line = true
